### PR TITLE
Implemented majority of the packet library and a few missing functions

### PR DESCRIPTION
**Pull request by lapigr**
The rest of the packet functions i'm honestly not sure how they're implemented, aside from WaitForRecv which could probably just print "Received a packet with " + header but i'm not sure how ideal that is

Few scripts used in testing (both work as intended in game)

```
if GameState.IsInGame():
	Vulcan = Packet.COutPacket(0x013F)
	Vulcan.Encode4(0x17D7AF14)
	Vulcan.Encode1(0x00)
	for x in range(0,19):
		Vulcan.Encode4(0x00000000)
	Packet.SendPacket(Vulcan)
```

```
assert GameState.IsInGame()
	
assert not Terminal.IsRushing()
	
time.sleep(2)
Key.Press(0x31);
time.sleep(0.25);
Key.Press(0x31);
time.sleep(0.5);
Key.Press(0x31);
time.sleep(2);
Terminal.EnterCashShop()
time.sleep(1)
if GameState.IsInCashShop():
	Terminal.LeaveCashShop()
```

### CODE REVIEW

**Comment by Zephrym** [comment]
Thank you for this. Honestly the entire packet function was just a placeholder for now. Just gonna accept these merges and review later. Planned on fixing up alot of this stuff this weekend.

**Comment by Zephrym** [comment]
Merged

**Comment by lapigr** [comment]
Packet library came out looking pretty good I think, though there is no type checking now that I think about it so that might be something to note
```
Returns if you are in-game
Packet created with header: 0x013F
Appended: 0x17D7AF14
Appended: 0x00
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Appended: 0x00000000
Sending Packet: 0x013F 0x17D7AF14 0x00 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
```

**Comment by Zephrym** [comment]
I think Settings is the only class that uses assertion checks atm. Gonna add more in though. Thanks for this I was dreading doing the packet class because I hate working with packets.

**Pull request merged**
